name: Combined Docker Workflow

on:
  pull_request:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
      - run: |
          npm install
          npm run build
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.PR_DOCKER_USERNAME }}
          password: ${{ secrets.PR_DOCKER_PASSWORD }}
      - name: Build and push PR image
        if: github.event_name == 'pull_request'
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: false
      - name: Build and push release image
        if: github.actor == 'Niansuh' && github.event_name != 'pull_request'
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: niansuh/bingo:latest
      - name: Push to Hugging Face Hub
        if: github.actor == 'Niansuh' && github.event_name != 'pull_request'
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          HF_USERNAME: Niansuh
          SPACE_NAME: Bingo
        run: |
          git clone https://$HF_USERNAME:$HF_TOKEN@huggingface.co/spaces/$HF_USERNAME/$SPACE_NAME huggingface
          cd huggingface
          git config user.name Niansuh
          git config user.email niansuhtech@gmail.com
          echo "Last deploy time: $(date)" > DEPLOY_DATE.txt
          git add DEPLOY_DATE.txt
          git commit -am "auto deploy $(date)"
          git push https://$HF_USERNAME:$HF_TOKEN@huggingface.co/spaces/$HF_USERNAME/$SPACE_NAME main -f
